twig:
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    paths:
        'assets/images': images
        'assets/css': styles
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
